Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpu_mode = 'host-model'
    libvirt.cpus = 2
    libvirt.disk_bus = 'virtio'
    libvirt.disk_driver :cache => 'writeback'
    libvirt.driver = 'kvm'
    libvirt.memory = 2048
    libvirt.memorybacking :access, :mode => 'shared'
    libvirt.nested = true
    libvirt.nic_model_type = 'virtio'
    libvirt.storage :file, bus: 'virtio', cache: 'writeback'
    libvirt.video_type = 'virtio'
  end

  config.vm.define "head" do |head|
    head.vm.hostname = "head"
    head.vm.box = "roboxes-x64/ubuntu2204"
    head.vm.box_check_update = false
    head.vm.network :private_network, ip: "192.168.56.200"
    head.vm.provision "shell", path: "scripts/common.sh"
    head.vm.provision "shell", path: "scripts/head.sh"
  end

  config.vm.define "storage" do |storage|
    storage.vm.hostname = "storage"
    storage.vm.box = "roboxes-x64/ubuntu2204"
    storage.vm.network :private_network, ip: "192.168.56.210"
    storage.vm.provision "shell", path: "scripts/common.sh"
    storage.vm.provision "shell", path: "scripts/storage.sh"
  end

  config.vm.define "node01" do |node01|
    node01.vm.hostname = "node01"
    node01.vm.box = "roboxes-x64/ubuntu2204"
    node01.vm.box_check_update = false
    node01.vm.network :private_network, ip: "192.168.56.201"
    node01.vm.provision "shell", path: "scripts/common.sh"
    node01.vm.provision "shell", path: "scripts/nodes.sh"
  end

  config.vm.define "node02" do |node02|
    node02.vm.hostname = "node02"
    node02.vm.box = "roboxes-x64/ubuntu2204"
    node02.vm.box_check_update = false
    node02.vm.network :private_network, ip: "192.168.56.202"
    node02.vm.provision "shell", path: "scripts/common.sh"
    node02.vm.provision "shell", path: "scripts/nodes.sh"
  end

  config.vm.define "node03" do |node03|
    node03.vm.hostname = "node03"
    node03.vm.box = "roboxes-x64/ubuntu2204"
    node03.vm.box_check_update = false
    node03.vm.network :private_network, ip: "192.168.56.203"
    node03.vm.provision "shell", path: "scripts/common.sh"
    node03.vm.provision "shell", path: "scripts/nodes.sh"
  end

end
