Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |libvirt|
     libvirt.disk_bus = 'virtio'
     libvirt.disk_driver :cache => 'writeback'
     libvirt.driver = 'kvm'
     libvirt.memorybacking :access, :mode => 'shared'
     libvirt.nested = true
     libvirt.nic_model_type = 'virtio'
     libvirt.storage :file, bus: 'virtio', cache: 'writeback'
     libvirt.video_type = 'virtio'
  end

  config.vm.define "head" do |head|
    head.vm.hostname = "head"
    head.vm.box = "roboxes-x64/ubuntu2204"
    
    head.vm.network "private_network",
      ip: "10.10.10.100",
      netmask: "255.255.255.0",
      libvirt__network_name: "cluster",
      libvirt__dhcp_enabled: false

    head.vm.provider :libvirt do |libvirt|
      libvirt.cpus = '3'
      libvirt.memory = '2048'
    end

    head.vm.box_check_update = false

    head.vm.synced_folder "./data", "/data", type: "nfs", nfs_version: 4, nfs_udp: false
    head.vm.provision "shell", path: "data/scripts/common.sh"
    head.vm.provision "shell", path: "data/scripts/k8s-reqs.sh"
    head.vm.provision "shell", path: "data/scripts/head.sh"
    head.vm.provision "shell", path: "data/scripts/ansible.sh"

  end 

  config.vm.define "node01" do |node01|
    node01.vm.hostname = "node01"
    node01.vm.box = "roboxes-x64/ubuntu2204"

    node01.vm.network "private_network",
      ip: "10.10.10.101",
      netmask: "255.255.255.0",
      mac: "3a:15:0b:5f:61:87",
      libvirt__network_name: "cluster",
      libvirt__dhcp_enabled: false,
      libvirt__host_ip: '10.10.10.100'
    
    node01.vm.provider :libvirt do |libvirt|
      libvirt.cpus = '2'
      libvirt.memory = '2048'
      libvirt.boot 'hd'
    end

    node01.vm.synced_folder "./data", "/data", type: "nfs", nfs_version: 4, nfs_udp: false
    node01.vm.provision "shell", path: "data/scripts/common.sh"
    node01.vm.provision "shell", path: "data/scripts/k8s-reqs.sh"
    node01.vm.provision "shell", path: "data/scripts/node-k8s.sh"

  end

  config.vm.define "node02" do |node02|
    node02.vm.hostname = "node02"
    node02.vm.box = "roboxes-x64/ubuntu2204"

    node02.vm.network "private_network",
      ip: "10.10.10.102",
      netmask: "255.255.255.0",
      mac: "0a:b5:2c:25:d9:a8",
      libvirt__network_name: "cluster",
      libvirt__dhcp_enabled: false,
      libvirt__host_ip: '10.10.10.100'

    node02.vm.provider :libvirt do |libvirt|
      libvirt.cpus = '2'
      libvirt.memory = '2048'
      libvirt.boot 'hd'
    end

    node02.vm.synced_folder "./data", "/data", type: "nfs", nfs_version: 4, nfs_udp: false
    node02.vm.provision "shell", path: "data/scripts/common.sh"
    #node02.vm.provision "shell", path: "data/scripts/slurm.sh"

  end

  config.vm.define "node03" do |node03|
    node03.vm.hostname = "node03"
    node03.vm.box = "roboxes-x64/ubuntu2204"

    node03.vm.network "private_network",
      ip: "10.10.10.103",
      netmask: "255.255.255.0",
      mac: "92:d7:d0:a1:5d:c9",
      libvirt__network_name: "cluster",
      libvirt__dhcp_enabled: false,
      libvirt__host_ip: '10.10.10.100'
    
    node03.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.cpus = '2'
      libvirt.memory = '2048'
      libvirt.boot 'hd'
    end

    node03.vm.synced_folder "./data", "/data", type: "nfs", nfs_version: 4, nfs_udp: false
    node03.vm.provision "shell", path: "data/scripts/common.sh"
    node03.vm.provision "shell", path: "data/scripts/k8s-reqs.sh"
  end

end
